- name: Gather facts from consul_server
  ansible.builtin.setup:
  delegate_to: "server1"
  delegate_facts: true
  register: consul_server_facts

- set_fact:
    consul_server_ip: "{{ consul_server_facts.ansible_facts.ansible_docker0.ipv4.address }}"

# - debug:
#     var: consul_server_facts.ansible_facts

- copy: content="{{ consul_server_facts.ansible_facts }}" dest=/tmp/consul_server_facts.json
