- name: Setup servers
  hosts:
    - consul_servers
    - consul_clients
  tasks:
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install apt packages
      ansible.builtin.apt:
        name:
          - net-tools
          - nmap

    - name: Install pip
      ansible.builtin.include_role:
        name: geerlingguy.pip

    - name: Disable UFW
      community.general.ufw:
        state: disabled
